spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleBookService
    username: postgres
    password: biba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect